apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-go-${APP_VERSION}
  labels:
    app: helloworld-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-go
      version: ${APP_VERSION}
  template:
    metadata:
      labels:
        app: helloworld-go
        version: ${APP_VERSION}
    spec:
      containers:
      - name: helloworld-go
        image: eu.gcr.io/plated-dryad-241619/helloworld-go:${DOCKER_TAG}
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8081
        env:
        - name: VERSION
          value: ${APP_VERSION}
        - name: POSTGRES_DB_HOST
          value: ${POSTGRES_DB_HOST}
        - name: POSTGRES_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          periodSeconds: 5
