apiVersion: v1
kind: Service
metadata:
  name: helloworld-go
  labels:
    app: helloworld-go
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: http-server
  selector:
    app: helloworld-go
